#include "component.h"
#include "transformcomponent.h"
#include "movementcomponent.h"
#include "gravitycomponent.h"
#include "controllercomponent.h"
#include "healthcomponent.h"
#include "spritecomponent.h"